#follows https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish Python 🐍 Windows wheel distribution 📦 to PyPI and TestPyPI

on: 
  workflow_dispatch:
    inputs:
      releasetype:
        description: "Is this a 'release' or a 'test'?" 
        required: true
        default: 'test'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: windows-latest

    steps:
    - name: Display phase
      run: echo "Deploying "${{github.event.inputs.releasetype}}" $INPUT_RELEASETYPE to PyPI"

    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools twine
        pip install -r requirements.txt

    - name: Build a test wheel
      if: github.event.inputs.releasetype == 'test'
      run: |
        $Env:PYTRECEVAL_NAME_SUFFIX = "-craigm"
        $DateTime = Get-Date -format yyyyMMdd_Hmmss
        $Env:PYTRECEVAL_VERSION_SUFFIX = "_$DateTime"
        python setup.py bdist_wheel
        dir dist/*

    - name: Build a release wheel
      if: github.event.inputs.releasetype == 'release'
      run: python setup.py bdist_wheel

    # Upload to TestPyPI
    - name: Upload to TestPyPI
      run: |
        python3 -m twine upload --verbose dist/*
      env:
        TWINE_USERNAME:  __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        TWINE_REPOSITORY: testpypi